const el = {
    time: document.getElementById("time"),
    date: document.getElementById("date"),
    main: document.querySelector("main"),
    bgselect: document.getElementById("bgselect"),
    fontselect: document.getElementById("fontselect"),
    opensettings: document.getElementById("settings-open"),
    buttons: document.getElementById("buttons"),
    openfullscreen: document.getElementById("fullscreen"),
    settings: document.getElementById("settings"),
    hideInFullscreen: document.getElementById("hideInFullscreen"),
    showSeconds: document.getElementById("showSeconds"),
    militaryTime: document.getElementById("24hourtime"),
    bgVideo: document.getElementById("bgVideo"),
    doTitle: document.getElementById("doTitle"),
    showDate: document.getElementById("showDate"),
    bgVideo: document.getElementById("bgVideo"),
    musicSelect: document.getElementById("musicselect"),
    showLofi: document.getElementById("show-lofi"),
    lofiPlayer: document.getElementById("lofi-player"),
    customVideoForm: document.getElementById("customVideoForm"),
    customVideoDialog: document.getElementById("customVideoDialog"),
    customVideoSubmit: document.getElementById("customVideoSubmit"),
    customVideoInput: document.getElementById("customVideoInput"),
    textEffectSelect: document.getElementById("texteffect")
}